POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "My First Blog Post",
  "author": "Faustine",
  "url": "https://fullstackopen.com",
  "likes": 100
}
###
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "mluukkai",
  "name": "Matti Luukkainen",
  "password": "salainen-salasana"
}