services:
  app:
    image: todo-backend
    build: .
    ports:
      - 3000:3000
    container_name: todo-backend-container
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    # We inject both the database and caching connection strings
    environment:
      - MONGO_URL=mongodb://mongo:27017/todo-app
      - REDIS_URL=redis://redis:6379
    command: sh -c "npm install && npm run dev"

  # THE DATABASE LAYER (Exercise 12.8)
  mongo:
    image: mongo
    container_name: todo-db-container
    ports:
      # Maps your host port 3456 to Mongo's internal port 27017
      - 3456:27017

  # THE CACHING LAYER (Exercise 12.9)
  redis:
    image: redis
    container_name: todo-redis-container
    ports:
      - 6379:6379