events { }

http {
  server {
    listen 80;

    # Route backend requests
    location /api/ {
      proxy_pass http://bloglist-backend:3003;
    }

    # Route frontend requests to our new static Nginx container
    location / {
      proxy_pass http://bloglist-frontend:80;
    }
  }
}