name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    
    # 2026 SECURITY STANDARD: Explicitly allow the token to write tags to repository contents
    permissions:
      contents: write
    
    defaults:
      run:
        working-directory: ./part11

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm install
        
      - name: Check style
        run: npm run eslint

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build

      - name: Deploy to Render
        run: curl "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch