services:
  # THE FRONTEND LAYER (DEVELOPMENT MODE)
  frontend:
    image: todo-frontend-dev
    build:
      context: ./todo-frontend
      dockerfile: dev.Dockerfile
    ports:
      - 5173:5173
    container_name: todo-frontend-dev-container
    environment:
      # This tells Vite to send all Axios requests to Nginx!
      - VITE_BACKEND_URL=http://localhost:8080/api
    volumes:
      - ./todo-frontend:/usr/src/app
      - /usr/src/app/node_modules

  # THE BACKEND LAYER (DEVELOPMENT MODE)
  app:
    image: todo-backend-dev
    build:
      context: ./todo-backend
      dockerfile: dev.Dockerfile
    ports:
      - 3000:3000
    container_name: todo-backend-dev-container
    volumes:
      - ./todo-backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - MONGO_URL=mongodb://mongo:27017/todo-app
      - REDIS_URL=redis://redis:6379

  # THE DATABASES
  mongo:
    image: mongo
    container_name: todo-db-container
    ports:
      - 3456:27017
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis
    container_name: todo-redis-container
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  # THE NGINX PROXY LAYER
  nginx:
    image: nginx:1.25-alpine
    container_name: todo-nginx-dev-container
    ports:
      - 8080:80
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - app

volumes:
  mongo_data:
  redis_data: