services:
  # THE FRONTEND LAYER (DEVELOPMENT MODE)
  frontend:
    image: todo-frontend-dev
    build:
      context: ./todo-frontend
      dockerfile: dev.Dockerfile
    # Vite development server runs on 5173
    ports:
      - 5173:5173
    container_name: todo-frontend-dev-container
    # We mount the volumes so Vite's hot-reloading works when you save a file!
    volumes:
      - ./todo-frontend:/usr/src/app
      - /usr/src/app/node_modules

  # THE REST OF THE FLEET STAYS EXACTLY THE SAME
  app:
    image: todo-backend
    build: ./todo-backend
    ports:
      - 3000:3000
    container_name: todo-backend-container
    volumes:
      - ./todo-backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - MONGO_URL=mongodb://mongo:27017/todo-app
      - REDIS_URL=redis://redis:6379
    command: sh -c "npm install && npm run dev"

  mongo:
    image: mongo
    container_name: todo-db-container
    ports:
      - 3456:27017
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis
    container_name: todo-redis-container
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data: