# events is required, but defaults are ok
events { }

# A http server, listening at port 80
http {
  server {
    listen 80;

    # Requests starting with root (/) are handled here
    location / {
      # The following 3 lines are absolutely required for Hot-Reloading (WebSockets) to work through Nginx!
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection 'upgrade';
      
      # Requests are directed to the frontend container
      proxy_pass http://frontend:5173;
    }

    # Requests starting with /api/ are handled here
    location /api/ {
      # The trailing slash here strips the /api/ prefix before sending it to the backend
      proxy_pass http://app:3000/;
    }
  }
}