# events is required, but defaults are ok
events { }

# A http server, listening at port 80
http {
  server {
    listen 80;

    # Requests starting with root (/) are handled here
    location / {
      # We route to the production frontend container's internal port 80
      proxy_pass http://frontend:80;
    }

    # Requests starting with /api/ are handled here
    location /api/ {
      proxy_pass http://app:3000/;
    }
  }
}